// ============================================================================
// ISKCON reading list — the books of His Divine Grace A.C. Bhaktivedanta
// Swami Prabhupada (distilled from the iskconbooks.com catalogue). Used by the
// Sadhana page's reading-book dropdown. "Other" allows free text.
// ============================================================================

export const SADHANA_BOOKS: string[] = [
  "Bhagavad-gita As It Is",
  "Srimad-Bhagavatam",
  "Sri Caitanya-caritamrta",
  "Krsna, The Supreme Personality of Godhead",
  "The Nectar of Devotion",
  "The Nectar of Instruction",
  "Sri Isopanisad",
  "Teachings of Lord Caitanya",
  "Teachings of Lord Kapila",
  "Teachings of Queen Kunti",
  "Teachings of Narada Muni",
  "The Science of Self-Realization",
  "The Path of Perfection",
  "The Perfection of Yoga",
  "Easy Journey to Other Planets",
  "Beyond Birth and Death",
  "A Second Chance",
  "Beyond Illusion and Doubt",
  "Civilization and Transcendence",
  "Dharma: The Way of Transcendence",
  "Elevation to Krishna Consciousness",
  "The Hare Krishna Challenge",
  "The Journey of Self-Discovery",
  "The Laws of Nature",
  "The Quest for Enlightenment",
  "Raja-Vidya: The King of Knowledge",
  "On the Way to Krsna",
  "Perfect Questions, Perfect Answers",
  "Chant and Be Happy",
  "Chanting Hare Krishna",
  "Coming Back",
  "Message of Godhead",
  "Light of the Bhagavata",
  "Sri Brahma Samhita",
  "Mukunda Mala Stotra",
  "Narada Bhakti Sutra",
  "A Beginner's Guide to Krishna Consciousness",
  "Bhakti — The Art of Eternal Love",
  "Krishna Consciousness: The Topmost Yoga System",
  "Krishna Consciousness: The Matchless Gift",
  "Krishna, The Reservoir of Pleasure",
  "Life Comes From Life",
  "Modern Times — Vedic Perspective",
  "Meditation",
  "Spiritual Yoga",
  "Finding Our Lost Happiness",
  "Introduction To Bhagavad Gita",
  "Consciousness: The Missing Link",
  "Stories From Puranas",
  "The Stories of Krsna",
  "Ramayana",
  "Lord Chaitanya: His Life & Teachings",
  "Transcendental Teachings of Prahlada Maharaja",
  "The Drama of Lord Jagannath",
  "Selected Verses From The Vedic Scriptures",
  "Shri Namamrita",
  "Vaishnava Song Book",
  "Srila Prabhupada-lilamrta",
  "Prabhupad",
  // Free-text fallback handled by the UI.
];
